services:
    postgres:
        image: postgres:16-alpine
        environment:
            POSTGRES_USER: "${POSTGRES_USER:-postgres}"
            POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-password}"
            POSTGRES_DB: "${POSTGRES_DB:-booking_db}"
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data

    redis:
        image: redis:7-alpine
        command: redis-server --appendonly yes
        ports:
            - "6379:6379"

    api:
        build: .
        env_file: .env
        environment:
            PYTHONPATH: /app/src

            DATABASE_URI: "${DATABASE_URI:-postgresql+asyncpg://postgres:${POSTGRES_PASSWORD:-password}@postgres:5432/booking_db}"
            REDIS_URI: "${REDIS_URI:-redis://redis:6379/0}"
            RATE_LIMIT_STORAGE_URI: "${RATE_LIMIT_STORAGE_URI:-redis://redis:6379/1}"
        ports:
            - "8000:8000"
        depends_on:
            postgres:
                condition: service_healthy
            redis:
                condition: service_started

    worker:
        build: .
        env_file: .env
        environment:
            PYTHONPATH: /app/src

            DATABASE_URI: "${DATABASE_URI:-postgresql+asyncpg://postgres:${POSTGRES_PASSWORD:-password}@postgres:5432/booking_db}"
            REDIS_URI: "${REDIS_URI:-redis://redis:6379/0}"
            
            CELERY_CUSTOM_WORKER_POOL: celery_aio_pool.pool:AsyncIOPool
        command: sh -c "celery -A tasks.booking_tasks worker --loglevel=info --pool=custom"
        depends_on:
            - api

volumes:
    pgdata:
